"""baseline

Revision ID: c76aa368577c
Revises: 
Create Date: 2026-04-06 16:37:51.352039
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'c76aa368577c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('task_args', sa.Text(), nullable=True),
    sa.Column('task_kwargs', sa.Text(), nullable=True),
    sa.Column('exception_type', sa.String(length=200), nullable=True),
    sa.Column('exception_message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_tasks_id'), 'dead_letter_tasks', ['id'], unique=False)
    op.create_table('curated_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('topic_tag', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_resources_id'), 'curated_resources', ['id'], unique=False)
    op.create_index(op.f('ix_curated_resources_topic_tag'), 'curated_resources', ['topic_tag'], unique=False)
    op.create_table('solidarity_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=150), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('emoji_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solidarity_posts_id'), 'solidarity_posts', ['id'], unique=False)
    op.create_table('material_confusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('section_label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['course_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'material_id', name='uq_confusion_per_material')
    )
    op.create_index(op.f('ix_material_confusions_id'), 'material_confusions', ['id'], unique=False)
    op.create_index(op.f('ix_material_confusions_material_id'), 'material_confusions', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_confusions_student_id'), 'material_confusions', ['student_id'], unique=False)
    op.add_column('assignments', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('require_gps', sa.Boolean(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('gps_longitude', sa.Float(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('gps_radius_meters', sa.Integer(), nullable=True))
    op.add_column('course_materials', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('course_materials', sa.Column('is_latest', sa.Boolean(), nullable=False))
    op.add_column('course_materials', sa.Column('replaces_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_materials', 'course_materials', ['replaces_id'], ['id'], ondelete='SET NULL')
    op.add_column('interventions', sa.Column('last_escalated_at', sa.DateTime(), nullable=True))
    op.add_column('interventions', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('lecture_notes', sa.Column('audio_file_path', sa.String(length=500), nullable=True))
    op.add_column('lecture_notes', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('material_reading_sessions', sa.Column('scroll_depth_pct', sa.Float(), nullable=True))
    op.add_column('material_reading_sessions', sa.Column('revisit_count', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('overtime_secs', sa.Integer(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('tab_switch_count', sa.Integer(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('flagged_overtime', sa.Boolean(), nullable=True))
    op.add_column('quizzes', sa.Column('difficulty', sa.String(length=20), nullable=True))
    op.add_column('risk_scores', sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('risk_scores', sa.Column('student_state', sa.String(length=20), nullable=True))
    op.add_column('risk_scores', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('sos_requests', sa.Column('hod_escalated_at', sa.DateTime(), nullable=True))
    op.add_column('sos_requests', sa.Column('followup_due_at', sa.DateTime(), nullable=True))
    op.add_column('sos_requests', sa.Column('followup_sent_at', sa.DateTime(), nullable=True))
    op.add_column('student_checkins', sa.Column('financial_stress', sa.String(length=20), nullable=True))
    op.add_column('student_results', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('student_tasks', sa.Column('reminder_at', sa.DateTime(), nullable=True))
    op.add_column('user_preferences', sa.Column('tone_preference', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('pending_email', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('pending_email_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pending_email_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('gps_opt_in', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gps_opt_in')
    op.drop_column('users', 'pending_email_expires')
    op.drop_column('users', 'pending_email_token')
    op.drop_column('users', 'pending_email')
    op.drop_column('user_preferences', 'tone_preference')
    op.drop_column('student_tasks', 'reminder_at')
    op.drop_column('student_results', 'is_published')
    op.drop_column('student_checkins', 'financial_stress')
    op.drop_column('sos_requests', 'followup_sent_at')
    op.drop_column('sos_requests', 'followup_due_at')
    op.drop_column('sos_requests', 'hod_escalated_at')
    op.drop_column('risk_scores', 'version')
    op.drop_column('risk_scores', 'student_state')
    op.drop_column('risk_scores', 'feature_snapshot')
    op.drop_column('quizzes', 'difficulty')
    op.drop_column('quiz_attempts', 'flagged_overtime')
    op.drop_column('quiz_attempts', 'tab_switch_count')
    op.drop_column('quiz_attempts', 'overtime_secs')
    op.drop_column('quiz_attempts', 'started_at')
    op.drop_column('notifications', 'priority')
    op.drop_column('material_reading_sessions', 'revisit_count')
    op.drop_column('material_reading_sessions', 'scroll_depth_pct')
    op.drop_column('lecture_notes', 'duration_seconds')
    op.drop_column('lecture_notes', 'audio_file_path')
    op.drop_column('interventions', 'version')
    op.drop_column('interventions', 'last_escalated_at')
    op.drop_constraint(None, 'course_materials', type_='foreignkey')
    op.drop_column('course_materials', 'replaces_id')
    op.drop_column('course_materials', 'is_latest')
    op.drop_column('course_materials', 'version')
    op.drop_column('attendance_sessions', 'gps_radius_meters')
    op.drop_column('attendance_sessions', 'gps_longitude')
    op.drop_column('attendance_sessions', 'gps_latitude')
    op.drop_column('attendance_sessions', 'require_gps')
    op.drop_column('assignments', 'is_published')
    op.drop_index(op.f('ix_material_confusions_student_id'), table_name='material_confusions')
    op.drop_index(op.f('ix_material_confusions_material_id'), table_name='material_confusions')
    op.drop_index(op.f('ix_material_confusions_id'), table_name='material_confusions')
    op.drop_table('material_confusions')
    op.drop_index(op.f('ix_solidarity_posts_id'), table_name='solidarity_posts')
    op.drop_table('solidarity_posts')
    op.drop_index(op.f('ix_curated_resources_topic_tag'), table_name='curated_resources')
    op.drop_index(op.f('ix_curated_resources_id'), table_name='curated_resources')
    op.drop_table('curated_resources')
    op.drop_index(op.f('ix_dead_letter_tasks_id'), table_name='dead_letter_tasks')
    op.drop_table('dead_letter_tasks')
    # ### end Alembic commands ###
