/**
 * Data constants and sub-components for the Landing Page.
 * Extracted to keep LandingPage.jsx focused on layout and composition.
 */
import {
  ShieldAlert,
  Bell,
  BrainCircuit,
  BarChart3,
  QrCode,
  MessageSquare,
  TrendingUp,
  AlertTriangle,
  Users,
  ListChecks,
  GraduationCap,
  BookOpen,
  UserPlus,
  ArrowRight,
  Building2,
  Activity,
  Eye,
  ClipboardCheck,
  Sparkles,
  UserCheck,
  Lightbulb,
  Target,
} from "lucide-react";

/* ------------------------------------------------------------------ */
/*  NAV & STATS DATA                                                   */
/* ------------------------------------------------------------------ */

export const NAV_LINKS = [
  { label: "About", target: "about" },
  { label: "Features", target: "features" },
  { label: "FAQ", target: "faq" },
  { label: "Contact", target: "contact" },
];

export const STATS = [
  { icon: Building2, value: "22", label: "Departments" },
  { icon: Sparkles, value: "24", label: "Risk Features" },
  { icon: BrainCircuit, value: "AI-Powered", label: "Analysis" },
  { icon: Activity, value: "Real-Time", label: "Monitoring" },
];

/* ------------------------------------------------------------------ */
/*  FEATURES DATA                                                      */
/* ------------------------------------------------------------------ */

export const FEATURES = [
  {
    icon: ShieldAlert,
    title: "Risk Detection",
    desc: "XGBoost ML model analyses 24 behavioural features to predict academic risk weekly with SHAP explanations.",
    details: {
      what: "Every week, the system collects your attendance, quiz scores, assignment submission rate, login activity, mood check-ins, SGPA, and more. An XGBoost machine learning model analyses these 24 behavioural signals and calculates a probability that you are at academic risk this semester.",
      how: "The model was trained on thousands of student records across all 22 departments. It uses SHAP (SHapley Additive exPlanations) to show you exactly which factors are contributing to your risk score \u2014 not just a number, but a reason.",
      for_students: "You see your own risk score on your Overview page. It updates every Monday. You will receive a notification when it changes.",
      for_lecturers: "You see a heatmap of all your students\u2019 risk levels per course. Students at High Risk are flagged with the top 3 contributing factors.",
      for_admin: "The DAP sees institution-wide risk distribution and trends across departments.",
    },
  },
  {
    icon: Bell,
    title: "Real-Time Alerts",
    desc: "Instant notifications when your risk level changes.",
    details: {
      what: "Notifications are pushed to your device the moment something changes \u2014 a new quiz is posted, attendance opens, risk level shifts, or a material is uploaded.",
      how: "Server-Sent Events (SSE) maintain a persistent connection per user. The backend fires events to your browser in real time without polling.",
      for_students: "Toast notifications appear on-screen. You never miss a quiz, assignment deadline, or attendance session.",
      for_lecturers: "You are notified when students submit work, mark attendance, or trigger SOS alerts.",
      for_admin: "System-wide event monitoring and real-time risk change alerts.",
    },
  },
  {
    icon: BrainCircuit,
    title: "AI Interventions",
    desc: "Personalised support messages generated by AI.",
    details: {
      what: "When a student\u2019s risk level changes, the system generates a personalised intervention message using their actual risk factors and behavioral data.",
      how: "Claude AI reads the student\u2019s SHAP explanation \u2014 the specific factors driving their risk \u2014 and generates an actionable, empathetic message tailored to their situation.",
      for_students: "You receive a notification with specific, personalised advice \u2014 not a generic warning.",
      for_lecturers: "You can review and edit the AI-generated message before it reaches the student. One click to generate, review, and send.",
      for_admin: "Efficacy reports show how many interventions were sent and whether students\u2019 risk levels improved afterwards.",
    },
  },
  {
    icon: BarChart3,
    title: "Engagement Tracking",
    desc: "Attendance, quizzes, assignments, mood tracking, and study time in one dashboard with a radar profile.",
    details: {
      what: "A comprehensive dashboard of 24 behavioral signals tracked over time \u2014 attendance trends, quiz performance, submission patterns, login frequency, and mood.",
      how: "Data is collected passively from your normal platform usage. The system aggregates and visualises trends so you can spot patterns early.",
      for_students: "Your Engagement page shows a radar chart of your behavioural signals and highlights which factors are strongest and weakest.",
      for_lecturers: "Course-level pulse analytics show class-wide engagement trends, helping you identify when attention is dropping.",
      for_admin: "Cross-department engagement analytics and semester-over-semester comparisons.",
    },
  },
  {
    icon: QrCode,
    title: "QR Attendance",
    desc: "Scan a QR code to mark attendance in seconds.",
    details: {
      what: "Lecturers open an attendance session with one click. A QR code and 6-character code are generated. Students scan or type the code to mark attendance within the time window.",
      how: "QR codes use HMAC-SHA256 signatures that rotate every 90 seconds with cryptographic verification. A one-slot grace window handles slight delays.",
      for_students: "You get a notification when attendance opens. Scan the QR code or type the code \u2014 attendance is marked in seconds.",
      for_lecturers: "Open a session, display the QR, and watch the attendance count update in real time. No paper sign-in sheets.",
      for_admin: "Session-level attendance analytics across all courses and departments.",
    },
  },
  {
    icon: MessageSquare,
    title: "AI Tutor",
    desc: "Ask questions about your course material and get AI-powered answers.",
    details: {
      what: "An AI-powered tutor that answers your course-specific questions using your uploaded course materials as its knowledge base.",
      how: "Claude AI has access to all materials uploaded for your course \u2014 lecture notes, PDFs, slides. It answers questions grounded in your actual curriculum.",
      for_students: "Ask any question about your course material and get a detailed, accurate answer instantly. Available 24/7.",
      for_lecturers: "Students can get help outside office hours. Usage analytics show which topics students are asking about most.",
      for_admin: "AI feature usage reports and cost monitoring.",
    },
  },
  {
    icon: TrendingUp,
    title: "Recovery Path",
    desc: "See exactly what you need to do to reduce your risk level.",
    details: {
      what: "A structured recovery plan generated for students identified as at-risk. Provides week-by-week milestones and actionable steps to improve.",
      how: "Based on your specific risk factors and SHAP explanation, the system creates a personalised path with achievable weekly targets.",
      for_students: "A clear roadmap from your current risk level to a safe zone, with weekly check-ins to track your progress.",
      for_lecturers: "Visibility into which students are on recovery paths and their progress towards milestones.",
      for_admin: "Recovery path completion rates and success metrics across the institution.",
    },
  },
  {
    icon: AlertTriangle,
    title: "SOS System",
    desc: "Press one button to alert your lecturer when you need urgent help.",
    details: {
      what: "An emergency support button for students who need urgent academic, financial, emotional, or health support.",
      how: "One tap sends a categorised alert to your course lecturer and department admin. The response team sees a priority dashboard.",
      for_students: "Select your concern category and send an SOS. Your lecturer and admin are notified immediately. You can send up to 3 per day.",
      for_lecturers: "SOS alerts appear on your dashboard with category and urgency. Respond directly through the platform.",
      for_admin: "SOS dashboard shows trends, response times, and category breakdowns across the institution.",
    },
  },
  {
    icon: Users,
    title: "Peer Study",
    desc: "Get matched with study partners based on your courses and performance.",
    details: {
      what: "Connect with classmates for collaborative study sessions. Create or join study groups based on your courses.",
      how: "The system suggests study partners based on course enrollment and complementary strengths. Group creation is one click.",
      for_students: "Find study partners in your course, create study sessions, and invitations are sent automatically.",
      for_lecturers: "See peer study participation rates as part of student engagement metrics.",
      for_admin: "Institutional peer study analytics and collaboration metrics.",
    },
  },
  {
    icon: ListChecks,
    title: "Smart To-Do",
    desc: "AI-generated task lists that prioritise your most important actions.",
    details: {
      what: "An intelligent task manager that auto-creates tasks from your quizzes, assignments, and course deadlines with smart priority ranking.",
      how: "Tasks are automatically generated when lecturers publish quizzes or assignments. Priority is computed based on deadline proximity and course weight.",
      for_students: "Your to-do list is pre-populated with everything due. Priorities adjust as deadlines approach. Complete tasks to stay on track.",
      for_lecturers: "Task completion rates per assignment provide insight into student engagement and workload management.",
      for_admin: "Platform-wide task completion analytics and deadline adherence.",
    },
  },
];

/* ------------------------------------------------------------------ */
/*  HOW IT WORKS DATA                                                  */
/* ------------------------------------------------------------------ */

export const HOW_STEPS = [
  {
    icon: UserPlus,
    title: "Enroll",
    desc: "Register with your matric number and join your courses.",
  },
  {
    icon: ClipboardCheck,
    title: "Engage",
    desc: "Attend classes, take quizzes, submit assignments on time.",
  },
  {
    icon: Eye,
    title: "Get Insights",
    desc: "The AI analyses your behaviour and computes your weekly risk score.",
  },
  {
    icon: Target,
    title: "Improve",
    desc: "Follow personalised recommendations to improve your grades.",
  },
];

/* ------------------------------------------------------------------ */
/*  FAQ DATA                                                           */
/* ------------------------------------------------------------------ */

export const FAQ_DATA = [
  {
    q: "Who can use this system?",
    a: "All students, lecturers, and administrators at Maranatha University. Students register with their matric number, lecturers with their staff ID, and Deans/HODs register using a pre-approved staff ID from the Director of Academic Planning.",
  },
  {
    q: "How does the risk detection work?",
    a: "The system tracks 24 key behavioural indicators including attendance rate, quiz scores, assignment submissions, late submission patterns, login frequency, consecutive absences, mood check-ins, SGPA, help-seeking ratio, peer interaction, and more. An XGBoost machine learning model analyses these weekly and assigns a risk level (Low, Medium, or High) to each student in each course.",
  },
  {
    q: "What happens if I'm flagged as High Risk?",
    a: "You'll receive a notification with a personalised intervention recommendation. Your lecturer will also be alerted and may reach out to offer support. You can see exactly what you need to improve on your Recovery Path page.",
  },
  {
    q: "Is my data private?",
    a: "Yes. Only you can see your own risk scores. Your lecturer can see risk levels for students in their courses only. Administrators see aggregate statistics, not individual student data, unless they have a specific academic reason documented in the audit log.",
  },
  {
    q: "Can I use the system on my phone?",
    a: "Yes. The system is a Progressive Web App (PWA) — fully responsive on any device. You can install it to your home screen for a native app-like experience with offline support and push notifications.",
  },
  {
    q: "What if I disagree with my risk level?",
    a: "You can submit a weekly self-reflection to share how you feel about your progress. Your lecturer sees these reflections and can adjust their support accordingly. You can also use the Predictive Simulator to see how improving specific metrics would change your risk level.",
  },
  {
    q: "How do I contact support?",
    a: "Use the SOS button on your dashboard for urgent academic help, or contact the admin office at admin@maranatha.edu.ng.",
  },
];

/* ------------------------------------------------------------------ */
/*  ROLE CARDS DATA                                                    */
/* ------------------------------------------------------------------ */

export const ROLE_CARDS = [
  {
    icon: GraduationCap,
    role: "I'm a Student",
    desc: "Register with your matric number and start tracking your academic progress.",
    path: "/register/student",
  },
  {
    icon: BookOpen,
    role: "I'm a Lecturer",
    desc: "Join with your registered email and monitor student performance across your courses.",
    path: "/register/lecturer",
  },
  {
    icon: ShieldAlert,
    role: "I'm an Administrator",
    desc: "Register as Dean or HOD with DAP approval. Requires a pre-approved staff ID.",
    path: "/register/admin",
  },
];

/* ------------------------------------------------------------------ */
/*  ANIMATION VARIANTS                                                 */
/* ------------------------------------------------------------------ */

export const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" } },
};

export const staggerContainer = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.1 } },
};

export const staggerChild = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" } },
};

/* ------------------------------------------------------------------ */
/*  FLOW DIAGRAM COMPONENT                                             */
/* ------------------------------------------------------------------ */

const FLOW_NODES = [
  { label: "Student Activity", icon: UserCheck },
  { label: "ML Analysis", icon: BrainCircuit },
  { label: "Risk Detection", icon: ShieldAlert },
  { label: "Intervention", icon: Lightbulb },
  { label: "Recovery", icon: TrendingUp },
];

export function FlowDiagram({ direction = "horizontal" }) {
  const isH = direction === "horizontal";
  return (
    <div
      className={`flex ${isH ? "flex-row" : "flex-col"} items-center justify-center gap-0`}
    >
      {FLOW_NODES.map((node, i) => {
        const Icon = node.icon;
        return (
          <div key={node.label} className={`flex ${isH ? "flex-row" : "flex-col"} items-center`}>
            <div className="flex flex-col items-center gap-2">
              <div className="w-14 h-14 rounded-xl bg-navy-500/80 border border-gold-400/30 flex items-center justify-center">
                <Icon size={22} className="text-gold-400" />
              </div>
              <span className="text-xs text-white/80 font-medium text-center w-20 leading-tight">
                {node.label}
              </span>
            </div>
            {i < FLOW_NODES.length - 1 && (
              <div className={`${isH ? "mx-1" : "my-1"} flex items-center justify-center`}>
                <ArrowRight
                  size={16}
                  className={`text-gold-400/60 ${!isH ? "rotate-90" : ""}`}
                />
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  HERO SVG ILLUSTRATION                                              */
/* ------------------------------------------------------------------ */

export function HeroIllustration() {
  return (
    <svg viewBox="0 0 400 360" fill="none" className="w-full h-auto max-w-md mx-auto">
      {/* Node: Student Activity */}
      <rect x="140" y="10" width="120" height="44" rx="10" fill="#1e3a5f" stroke="#fbbf24" strokeWidth="1.5" />
      <text x="200" y="36" textAnchor="middle" fill="white" fontSize="11" fontWeight="600">
        Student Activity
      </text>

      {/* Arrow down */}
      <line x1="200" y1="54" x2="200" y2="80" stroke="#fbbf24" strokeWidth="1.5" />
      <polygon points="194,76 200,86 206,76" fill="#fbbf24" />

      {/* Node: ML Analysis */}
      <rect x="140" y="86" width="120" height="44" rx="10" fill="#1e3a5f" stroke="#fbbf24" strokeWidth="1.5" />
      <text x="200" y="112" textAnchor="middle" fill="white" fontSize="11" fontWeight="600">
        ML Analysis
      </text>

      {/* Fork: two arrows */}
      <line x1="200" y1="130" x2="200" y2="150" stroke="#fbbf24" strokeWidth="1.5" />
      <line x1="200" y1="150" x2="100" y2="170" stroke="#fbbf24" strokeWidth="1.5" />
      <line x1="200" y1="150" x2="300" y2="170" stroke="#fbbf24" strokeWidth="1.5" />
      <polygon points="94,166 100,176 106,166" fill="#fbbf24" />
      <polygon points="294,166 300,176 306,166" fill="#fbbf24" />

      {/* Left node: Risk Score */}
      <rect x="40" y="176" width="120" height="44" rx="10" fill="#7f1d1d" stroke="#fbbf24" strokeWidth="1.5" />
      <text x="100" y="202" textAnchor="middle" fill="white" fontSize="11" fontWeight="600">
        Risk Score
      </text>

      {/* Right node: SHAP Explanation */}
      <rect x="240" y="176" width="120" height="44" rx="10" fill="#1e3a5f" stroke="#fbbf24" strokeWidth="1.5" />
      <text x="300" y="202" textAnchor="middle" fill="white" fontSize="11" fontWeight="600">
        SHAP Explanation
      </text>

      {/* Merge arrows */}
      <line x1="100" y1="220" x2="100" y2="240" stroke="#fbbf24" strokeWidth="1.5" />
      <line x1="300" y1="220" x2="300" y2="240" stroke="#fbbf24" strokeWidth="1.5" />
      <line x1="100" y1="240" x2="200" y2="260" stroke="#fbbf24" strokeWidth="1.5" />
      <line x1="300" y1="240" x2="200" y2="260" stroke="#fbbf24" strokeWidth="1.5" />
      <polygon points="194,256 200,266 206,256" fill="#fbbf24" />

      {/* Node: Personalised Intervention */}
      <rect x="120" y="266" width="160" height="44" rx="10" fill="#065f46" stroke="#fbbf24" strokeWidth="1.5" />
      <text x="200" y="292" textAnchor="middle" fill="white" fontSize="11" fontWeight="600">
        Personalised Intervention
      </text>

      {/* Arrow down */}
      <line x1="200" y1="310" x2="200" y2="330" stroke="#fbbf24" strokeWidth="1.5" />
      <polygon points="194,326 200,336 206,326" fill="#fbbf24" />

      {/* Node: Recovery */}
      <rect x="140" y="336" width="120" height="44" rx="10" fill="#1e3a5f" stroke="#fbbf24" strokeWidth="1.5" />
      <text x="200" y="362" textAnchor="middle" fill="white" fontSize="11" fontWeight="600">
        Recovery Path
      </text>
    </svg>
  );
}
